### PR TITLE
Upgrade draft-js to 0.7.0 and mentioning plugin to 1.1.1

### PR DESCRIPTION
**Pull request by thammerl**
I'd like to try to upgrade draft-js and draft-js-mention-plugin to their latest versions. Maybe this solves the mentioning in Safari 8.

@mcallistersean If you merge this could you please deploy a new version to production so Isabella can test it?

### CODE REVIEW

**Comment by mcallistersean** [comment]
@thammerl merged, rebuilt, deployed
thanks!

**Comment by thammerl** [comment]
Thank you. Unfortunately that didn't help. :(

**Comment by mcallistersean** [comment]
@thammerl worth a try. do you have any kind of stacktrace for me?

**Comment by thammerl** [comment]
Nothing. Can't find any error in the console. Just as if the plugin wasn't there.

**Pull request merged**
